# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
before_install:
 - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
r_binary_packages:
  - rgdal
